name: Debian Package

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use
          docker buildx inspect --bootstrap

  build_x86_64:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Create Debian Package for x86_64
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3-virtualenv dpkg-dev
          mkdir -p build
          ./.build.sh
      - name: Upload Debian Package for x86_64
        uses: actions/upload-artifact@v4
        with:
          name: python3-pymainprocess-amd64.deb
          path: build/*.deb

  build_x86:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Create Dockerfile for x86
        run: |
          echo "FROM i386/ubuntu:latest" > Dockerfile.x86
          echo "RUN apt-get update -qq && apt-get install -y python3-virtualenv dpkg-dev" >> Dockerfile.x86
          echo "COPY . /workspace" >> Dockerfile.x86
          echo "WORKDIR /workspace" >> Dockerfile.x86
          echo "RUN mkdir -p build && ./.build.sh" >> Dockerfile.x86
      - name: Create Debian Package for x86
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform linux/386 -f Dockerfile.x86 -t myimage:386 .
          docker run --rm myimage:386 /bin/bash -c "
            sudo apt-get update -qq &&
            sudo apt-get install -y python3-virtualenv dpkg-dev &&
            mkdir -p build &&
            ./.build.sh"
      - name: Upload Debian Package for x86
        uses: actions/upload-artifact@v4
        with:
          name: python3-pymainprocess-i386.deb
          path: build/*.deb

  build_aarch64:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Create Dockerfile for aarch64
        run: |
          echo "FROM arm64v8/ubuntu:latest" > Dockerfile.aarch64
          echo "RUN apt-get update -qq && apt-get install -y python3-virtualenv dpkg-dev" >> Dockerfile.aarch64
          echo "COPY . /workspace" >> Dockerfile.aarch64
          echo "WORKDIR /workspace" >> Dockerfile.aarch64
          echo "RUN mkdir -p build && ./.build.sh" >> Dockerfile.aarch64
      - name: Create Debian Package for aarch64
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform linux/arm64 -f Dockerfile.aarch64 -t myimage:arm64 .
          docker run --rm myimage:arm64 /bin/bash -c "
            sudo apt-get update -qq &&
            sudo apt-get install -y python3-virtualenv dpkg-dev &&
            mkdir -p build &&
            ./.build.sh"
            - name: Upload Debian Package for s390x
        uses: actions/upload-artifact@v4
        with:
          name: python3-pymainprocess-s390x.deb
          path: build/*.deb

  build_ppc64le:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Create Dockerfile for ppc64le
        run: |
          echo "FROM ppc64le/ubuntu:latest" > Dockerfile.ppc64le
          echo "RUN apt-get update -qq && apt-get install -y python3-virtualenv dpkg-dev" >> Dockerfile.ppc64le
          echo "COPY . /workspace" >> Dockerfile.ppc64le
          echo "WORKDIR /workspace" >> Dockerfile.ppc64le
          echo "RUN mkdir -p build && ./.build.sh" >> Dockerfile.ppc64le
      - name: Create Debian Package for ppc64le
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform linux/ppc64le -f Dockerfile.ppc64le -t myimage:ppc64le .
          docker run --rm myimage:ppc64le /bin/bash -c "
            sudo apt-get update -qq &&
            sudo apt-get install -y python3-virtualenv dpkg-dev &&
            mkdir -p build &&
            ./.build.sh"
      - name: Upload Debian Package for ppc64le
        uses: actions/upload-artifact@v4
        with:
          name: python3-pymainprocess-ppc64el.deb
          path: build/*.deb